// <auto-generated />
using System;
using AppointmentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppointmentService.Migrations
{
    [DbContext(typeof(AppointmentDbContext))]
    [Migration("20260527192725_CompleteAppointmentWorkflow")]
    partial class CompleteAppointmentWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppointmentService.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("PatientNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PatientPhoneSnapshot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("QueueNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<TimeOnly>("SlotTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId", "AppointmentDate", "SlotTime")
                        .IsUnique()
                        .HasFilter("\"Status\" <> 'Cancelled'");

                    b.ToTable("Appointments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateOnly(2026, 5, 28),
                            CreatedAt = new DateTime(2026, 5, 28, 1, 30, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            PatientId = 10,
                            PatientNameSnapshot = "Nguyen Van B",
                            PatientPhoneSnapshot = "0987654321",
                            QueueNumber = 3,
                            Reason = "Kham tim mach dinh ky",
                            SlotTime = new TimeOnly(8, 30, 0),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateOnly(2026, 5, 28),
                            CreatedAt = new DateTime(2026, 5, 28, 2, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            PatientId = 11,
                            PatientNameSnapshot = "Tran Thi C",
                            PatientPhoneSnapshot = "0912345678",
                            Reason = "Sot va ho",
                            SlotTime = new TimeOnly(13, 30, 0),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("AppointmentService.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("ExamFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80",
                            CreatedAt = new DateTime(2026, 5, 28, 1, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1985, 3, 12),
                            Degree = "Thac si, Bac si CKI",
                            Description = "Chuyen kham va dieu tri benh ly tim mach, tang huyet ap va roi loan nhip tim.",
                            Email = "nguyenvana@clinic.test",
                            ExamFee = 150000m,
                            ExperienceYears = 12,
                            FullName = "Bac si Nguyen Van A",
                            Gender = "Male",
                            IsActive = true,
                            Phone = "0901000001",
                            RoomNumber = "A-201",
                            SpecialtyId = 1
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80",
                            CreatedAt = new DateTime(2026, 5, 28, 1, 5, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1988, 7, 24),
                            Degree = "Bac si CKII",
                            Description = "Phu trach tham kham nhi khoa, tu van dinh duong va theo doi suc khoe tre em.",
                            Email = "tranthib@clinic.test",
                            ExamFee = 120000m,
                            ExperienceYears = 10,
                            FullName = "Bac si Tran Thi B",
                            Gender = "Female",
                            IsActive = true,
                            Phone = "0901000002",
                            RoomNumber = "B-102",
                            SpecialtyId = 2
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=600&q=80",
                            CreatedAt = new DateTime(2026, 5, 28, 1, 10, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1990, 11, 5),
                            Degree = "Bac si Da lieu",
                            Description = "Tu van va dieu tri cac van de ve da, mun, di ung da va cham soc da.",
                            Email = "levanc@clinic.test",
                            ExamFee = 100000m,
                            ExperienceYears = 8,
                            FullName = "Bac si Le Van C",
                            Gender = "Male",
                            IsActive = true,
                            Phone = "0901000003",
                            RoomNumber = "C-305",
                            SpecialtyId = 3
                        });
                });

            modelBuilder.Entity("AppointmentService.Models.DoctorSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("SlotDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId", "WorkDate", "StartTime")
                        .IsUnique();

                    b.ToTable("DoctorSchedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 2,
                            EndTime = new TimeOnly(11, 30, 0),
                            IsAvailable = true,
                            SlotDurationMinutes = 30,
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 5, 28)
                        },
                        new
                        {
                            Id = 2,
                            DoctorId = 1,
                            EndTime = new TimeOnly(16, 30, 0),
                            IsAvailable = true,
                            SlotDurationMinutes = 30,
                            StartTime = new TimeOnly(13, 0, 0),
                            WorkDate = new DateOnly(2026, 5, 28)
                        },
                        new
                        {
                            Id = 3,
                            DoctorId = 3,
                            EndTime = new TimeOnly(10, 0, 0),
                            IsAvailable = true,
                            SlotDurationMinutes = 30,
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 5, 28)
                        });
                });

            modelBuilder.Entity("AppointmentService.Models.QueueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("QueueDate")
                        .HasColumnType("date");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("QueueDate", "QueueNumber")
                        .IsUnique();

                    b.ToTable("WaitingQueues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2026, 5, 28, 1, 35, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            PatientId = 10,
                            QueueDate = new DateOnly(2026, 5, 28),
                            QueueNumber = 3,
                            Status = "Waiting"
                        });
                });

            modelBuilder.Entity("AppointmentService.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Specialties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tim mach"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nhi khoa"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Da lieu"
                        });
                });

            modelBuilder.Entity("AppointmentService.Models.Appointment", b =>
                {
                    b.HasOne("AppointmentService.Models.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentService.Models.Doctor", b =>
                {
                    b.HasOne("AppointmentService.Models.Specialty", null)
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentService.Models.DoctorSchedule", b =>
                {
                    b.HasOne("AppointmentService.Models.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentService.Models.QueueEntry", b =>
                {
                    b.HasOne("AppointmentService.Models.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppointmentService.Models.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
