// <auto-generated />
using System;
using AppointmentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppointmentService.Migrations
{
    [DbContext(typeof(AppointmentDbContext))]
    [Migration("20260525074704_InitialPostgresCreate")]
    partial class InitialPostgresCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppointmentService.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("PatientNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PatientPhoneSnapshot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("SlotTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId", "AppointmentDate", "SlotTime")
                        .IsUnique()
                        .HasFilter("\"Status\" <> 'Cancelled'");

                    b.ToTable("Appointments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateOnly(2026, 5, 22),
                            CreatedAt = new DateTime(2026, 5, 22, 1, 30, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            PatientId = 10,
                            PatientNameSnapshot = "Nguyen Van B",
                            PatientPhoneSnapshot = "0987654321",
                            QueueNumber = 3,
                            SlotTime = new TimeOnly(8, 30, 0),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateOnly(2026, 5, 22),
                            CreatedAt = new DateTime(2026, 5, 22, 2, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            PatientId = 11,
                            PatientNameSnapshot = "Tran Thi C",
                            PatientPhoneSnapshot = "0912345678",
                            QueueNumber = 1,
                            SlotTime = new TimeOnly(13, 30, 0),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("AppointmentService.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ExamFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExamFee = 120000m,
                            Name = "Bac si Minh",
                            SpecialtyId = 2
                        },
                        new
                        {
                            Id = 2,
                            ExamFee = 150000m,
                            Name = "Bac si A",
                            SpecialtyId = 1
                        });
                });

            modelBuilder.Entity("AppointmentService.Models.DoctorSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId", "WorkDate", "StartTime")
                        .IsUnique();

                    b.ToTable("DoctorSchedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 2,
                            EndTime = new TimeOnly(11, 30, 0),
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 5, 22)
                        },
                        new
                        {
                            Id = 2,
                            DoctorId = 1,
                            EndTime = new TimeOnly(16, 30, 0),
                            StartTime = new TimeOnly(13, 0, 0),
                            WorkDate = new DateOnly(2026, 5, 22)
                        });
                });

            modelBuilder.Entity("AppointmentService.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Specialties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tim mach"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Noi tong quat"
                        });
                });

            modelBuilder.Entity("AppointmentService.Models.Appointment", b =>
                {
                    b.HasOne("AppointmentService.Models.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentService.Models.Doctor", b =>
                {
                    b.HasOne("AppointmentService.Models.Specialty", null)
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentService.Models.DoctorSchedule", b =>
                {
                    b.HasOne("AppointmentService.Models.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
