version: '3.8'

services:
  # Message Broker (RabbitMQ) cho toàn hệ thống
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: pharmacy-rabbitmq
    ports:
      - "5672:5672"      # Cổng kết nối AMQP của ứng dụng
      - "15672:15672"    # Giao diện quản lý UI Admin (User/Password mặc định: guest/guest)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - clinic-network

  # Hệ quản trị cơ sở dữ liệu PostgreSQL cho PharmacyDB
  pharmacy-db:
    image: postgres:15-alpine
    container_name: pharmacy-postgres
    environment:
      POSTGRES_DB: PharmacyDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"      # Cổng kết nối CSDL cục bộ
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clinic-network

volumes:
  rabbitmq_data:
  postgres_data:

networks:
  clinic-network:
    name: clinic-shared-network
    driver: bridge
